version: "3"

services:
  nginx-global:
#    image: "nginx"
    image: "gaciaga/nginx-vts"
    container_name: "nginx-show"
    user: root
    privileged: true
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./web:/home/web:ro"
      - "./nginx/:/etc/nginx/:ro"
    restart: always
